[package]
name = "multiples_of_3_and_5_multithreaded"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiqueue = "0.3.2"
atomic-counter = "1.0.1"


